minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0

shellEmulator: true

overrides:
  source-map-js: 1.2.2
  why-is-node-running: 3.2.1

allowBuilds:
  esbuild: true
