import type { BaseReading, TagObserver } from '../../scripts/contract/bump.js'
import type { SurfaceReading } from '../../scripts/contract/semantic-diff.js'
import { execFileSync } from 'node:child_process'
import { existsSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import process from 'node:process'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { baseReading, baseTag, generatedBase, isWeaker, requiredLevel } from '../../scripts/contract/bump.js'
import { isUnbaselined, requiredChange, SECTIONS, unbaselined } from '../../scripts/contract/semantic-diff.js'
import { SURFACE_VERSION } from '../../scripts/contract/surface.js'
import { fixtureSurface, reading } from './surface-fixture.js'

const GENERATED_NOTE = 'generated by the fake observer'

function generatedReading(): SurfaceReading {
  return { ...reading(fixtureSurface()), exits: unbaselined('exit codes are not observable from the tag\'s output') }
}

function recordingGenerator(): { calls: string[], generate: (why: string) => BaseReading } {
  const calls: string[] = []
  return { calls, generate: (why) => {
    calls.push(why)
    return { reading: generatedReading(), note: GENERATED_NOTE }
  } }
}

function wholeBaseReasons(base: BaseReading): string[] {
  return SECTIONS.map((section) => {
    const value = base.reading[section]
    return isUnbaselined(value) ? value.unbaselined : `${section} is baselined`
  })
}

describe('base selection', () => {
  it('a tag file of the same surfaceVersion is the base, and nothing is generated', () => {
    const recorded = fixtureSurface()
    const { calls, generate } = recordingGenerator()
    const base = baseReading(recorded, 'v0.19.0', generate)
    expect(base.reading).toEqual(recorded)
    expect(calls).toEqual([])
    expect(requiredChange(base.reading, fixtureSurface()).level).toBe('none')
  })

  it('a tag file of another surfaceVersion is not the base: the base is generated from the tag\'s code', () => {
    const { calls, generate } = recordingGenerator()
    const base = baseReading({ ...fixtureSurface(), surfaceVersion: SURFACE_VERSION - 1 }, 'v0.18.0', generate)
    expect(calls).toEqual([`v0.18.0 carries contract/surface.json of surfaceVersion ${SURFACE_VERSION - 1}, this generator writes ${SURFACE_VERSION}`])
    expect(base.note).toBe(GENERATED_NOTE)
    expect(base.reading).toEqual(generatedReading())
  })

  it('a tag file with no surfaceVersion reads as version 1 and the base is generated', () => {
    const { surfaceVersion: _, ...unversioned } = fixtureSurface()
    const { calls, generate } = recordingGenerator()
    baseReading(unversioned, 'v0.18.0', generate)
    expect(calls).toEqual([expect.stringContaining('surfaceVersion 1,')])
  })

  it('a tag with no file has its base generated', () => {
    const { calls, generate } = recordingGenerator()
    const base = baseReading(null, 'v0.17.2', generate)
    expect(calls).toEqual(['v0.17.2 carries no contract/surface.json'])
    expect(requiredChange(base.reading, fixtureSurface())).toEqual({
      level: 'breaking',
      reasons: ['exits: unbaselined in the base (exit codes are not observable from the tag\'s output), so every item in it counts as changed'],
    })
  })

  it('the fixture reading is a whole surface', () => {
    expect(Object.keys(reading(fixtureSurface())).sort()).toEqual([...SECTIONS].sort())
  })
})

describe('the required level', () => {
  it('before 1.0: none → none, additive → patch, breaking → minor', () => {
    expect(requiredLevel('none', '0.18.0')).toBe('none')
    expect(requiredLevel('additive', '0.18.0')).toBe('patch')
    expect(requiredLevel('breaking', '0.18.0')).toBe('minor')
  })

  it('from 1.0: none → none, additive → minor, breaking → major', () => {
    expect(requiredLevel('none', '1.2.0')).toBe('none')
    expect(requiredLevel('additive', '1.2.0')).toBe('minor')
    expect(requiredLevel('breaking', '1.2.0')).toBe('major')
  })

  it('fails only a declared level weaker than the required one', () => {
    expect(isWeaker('patch', 'minor')).toBe(true)
    expect(isWeaker('none', 'patch')).toBe(true)
    expect(isWeaker('minor', 'minor')).toBe(false)
    expect(isWeaker('major', 'minor')).toBe(false)
    expect(isWeaker('none', 'none')).toBe(false)
  })
})

describe('base tag selection', () => {
  let repo: string
  let clock = Date.UTC(2026, 0, 1) / 1000

  function git(...args: string[]): string {
    clock += 3600
    const date = `${clock} +0000`
    return execFileSync('git', ['-c', 'user.name=t', '-c', 'user.email=t@example.com', '-c', 'commit.gpgsign=false', '-c', 'tag.gpgsign=false', ...args], {
      cwd: repo,
      encoding: 'utf8',
      env: { ...process.env, GIT_AUTHOR_DATE: date, GIT_COMMITTER_DATE: date },
    })
  }

  function commitAndTag(file: string, tag: string): void {
    writeFileSync(path.join(repo, file), tag)
    git('add', file)
    git('commit', '-q', '-m', tag)
    git('tag', '-a', tag, '-m', tag)
  }

  beforeAll(() => {
    repo = mkdtempSync(path.join(tmpdir(), 'construct-base-tag-'))
    git('init', '-q', '-b', 'main')
    commitAndTag('a.txt', 'v0.1.0')
    commitAndTag('b.txt', 'v0.2.0')
    git('checkout', '-q', '-b', 'side', 'v0.1.0')
    commitAndTag('c.txt', 'v0.3.0')
  })

  afterAll(() => rmSync(repo, { recursive: true, force: true }))

  it('on main, HEAD resolves to the latest tag it contains', () => {
    git('checkout', '-q', 'main')
    expect(baseTag(repo)).toBe('v0.2.0')
  })

  it('on the side branch, HEAD resolves to its own tag', () => {
    git('checkout', '-q', 'side')
    expect(baseTag(repo)).toBe('v0.3.0')
  })
})

describe('a base generated from a tag\'s code', () => {
  let repo: string

  function git(...args: string[]): string {
    return execFileSync('git', ['-c', 'user.name=t', '-c', 'user.email=t@example.com', '-c', 'commit.gpgsign=false', '-c', 'tag.gpgsign=false', ...args], { cwd: repo, encoding: 'utf8' })
  }

  function registeredWorktrees(): string {
    return git('worktree', 'list', '--porcelain')
  }

  function observer(overrides: Partial<TagObserver>, seen: string[]): TagObserver {
    return {
      install: worktree => seen.push(worktree),
      run: () => {},
      observe: () => generatedReading(),
      ...overrides,
    }
  }

  function expectRemoved(worktree: string | undefined): void {
    expect(worktree, 'the observer was never handed a worktree').toBeDefined()
    expect(existsSync(worktree!), `the worktree ${worktree} was left behind`).toBe(false)
    expect(registeredWorktrees(), `the worktree ${worktree} is still registered`).not.toContain(worktree!)
  }

  beforeAll(() => {
    repo = mkdtempSync(path.join(tmpdir(), 'construct-generated-base-'))
    git('init', '-q', '-b', 'main')
    writeFileSync(path.join(repo, 'a.txt'), 'a')
    git('add', 'a.txt')
    git('commit', '-q', '-m', 'a')
    git('tag', '-a', 'v0.1.0', '-m', 'v0.1.0')
  })

  afterAll(() => rmSync(repo, { recursive: true, force: true }))

  it('observes a worktree checked out at the tag, outside the repository, and removes it', () => {
    const seen: string[] = []
    const base = generatedBase(repo, 'v0.1.0', 'v0.1.0 carries no contract/surface.json', observer({
      observe: (worktree) => {
        expect(existsSync(path.join(worktree, 'a.txt'))).toBe(true)
        return generatedReading()
      },
    }, seen))
    expect(base.reading).toEqual(generatedReading())
    expect(base.note).toBe('v0.1.0 carries no contract/surface.json: the base is generated from v0.1.0\'s code')
    expect(seen[0].startsWith(repo)).toBe(false)
    expect(seen[0].startsWith(realpathSync(tmpdir()))).toBe(true)
    expectRemoved(seen[0])
  })

  it('a tag whose CLI does not install leaves the whole base unbaselined, naming the install step', () => {
    const seen: string[] = []
    const base = generatedBase(repo, 'v0.1.0', 'why', observer({
      install: (worktree) => {
        seen.push(worktree)
        throw new Error('ERR_PNPM_OUTDATED_LOCKFILE')
      },
    }, seen))
    expect(wholeBaseReasons(base)).toEqual(SECTIONS.map(() => 'the tag\'s CLI did not install (pnpm install --frozen-lockfile): ERR_PNPM_OUTDATED_LOCKFILE'))
    expect(requiredChange(base.reading, fixtureSurface()).level).toBe('breaking')
    expectRemoved(seen[0])
  })

  it('a tag whose CLI does not run leaves the whole base unbaselined, naming the run step', () => {
    const seen: string[] = []
    const base = generatedBase(repo, 'v0.1.0', 'why', observer({
      run: () => {
        throw new Error('Cannot find module')
      },
    }, seen))
    expect(wholeBaseReasons(base)).toEqual(SECTIONS.map(() => 'the tag\'s CLI did not run (--help): Cannot find module'))
    expect(base.note).toContain('the whole base is unbaselined')
    expectRemoved(seen[0])
  })

  it('removes the worktree when the observation throws', () => {
    const seen: string[] = []
    expect(() => generatedBase(repo, 'v0.1.0', 'why', observer({
      observe: () => {
        throw new Error('the observer broke')
      },
    }, seen))).toThrow('the observer broke')
    expectRemoved(seen[0])
  })
})
